spring.application.name=tuling-flight-booking
#spring.ai.openai.base-url=https://api.openai.com
#spring.ai.openai.base-url=https://api.xty.app
#spring.ai.openai.api-key=${OPEN_AI_KEY}

spring.ai.dashscope.api-key=${DASHSCOPE_API_KEY}
spring.ai.dashscope.chat.options.model=qwen-max

ai.vectorstore.type=redis

# Redis 连接配置
spring.data.redis.host=192.168.75.128
spring.data.redis.port=6379
spring.data.redis.password=123456
spring.data.redis.timeout=10s

# Redis 连接池参数（可选优化）
spring.data.redis.jedis.pool.max-active=200
spring.data.redis.jedis.pool.max-idle=10
spring.data.redis.jedis.pool.min-idle=5
spring.data.redis.jedis.pool.max-wait=5000ms

# Spring AI 向量存储配置
spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=airline-chat-index
spring.ai.vectorstore.redis.prefix=vector:airline: